name: Terraform Apply

on:
  workflow_call:
    inputs:
      working_directory:
        description: 'Terraform working directory'
        required: true
        type: string
      terraform_vars:
        description: 'Terraform variables to pass (JSON format)'
        required: false
        type: string
        default: '{}'
    secrets:
      AUTH0_CLIENT_SECRET:
        description: 'Auth0 Client Secret'
        required: false
      AWS_ACCESS_KEY_ID:
        description: 'AWS Access Key ID'
        required: false
      AWS_SECRET_ACCESS_KEY:
        description: 'AWS Secret Access Key'
        required: false

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Terraform Init
        working-directory: ${{ inputs.working_directory }}
        run: terraform init

      - name: Terraform Plan
        working-directory: ${{ inputs.working_directory }}
        run: |
          terraform apply -auto-approve -var="auth0_client_secret=${{ secrets.AUTH0_CLIENT_SECRET }}"

      - name: Terraform Apply
        working-directory: ${{ inputs.working_directory }}
        run: |
          terraform apply -auto-approve -var="auth0_client_secret=${{ secrets.AUTH0_CLIENT_SECRET }}"
